# -*- coding: utf-8 -*-
"""DataMerger

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g17FGOhg0ZCFnzTd_u7PGHO2XgEh7jVh

Code used to combine two .xlsx files based on columns

Donwload PyDrive package to link google drive to google colab

https://buomsoo-kim.github.io/colab/2018/04/16/Importing-files-from-Google-Drive-in-Google-Colab.md/
"""

!pip install PyDrive

"""import Pandas and pydrive"""

import pandas as pd

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

"""Authenticate google account"""

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

"""download files from google drive

To get the ID for the file you want to import from google drive, you need to run code above in java script

The quickest way to run this piece of javascript is to go to google and press ctrl + shift + j
"""

#var url = "your_shareable_link_to_file"
#function getIdFromUrl(url) { return url.match(/[-\w]{25,}/); }
#getIdFromUrl(url)

downloaded = drive.CreateFile({'id':"1VKwQcN1jyE1T9wAPl35_V45MOpJq_3S_"})   # replace the id with id of file you want to access
downloaded.GetContentFile('Chaves_NOIdates.xlsx')
downloaded2 = drive.CreateFile({'id':"1PSAnfk2wftZlmY17ofYuBxAVrwM16nMF"})   # replace the id with id of file you want to access
downloaded2.GetContentFile('Latlong_Chaves.xlsx')

"""* 1VKwQcN1jyE1T9wAPl35_V45MOpJq_3S_ <- Chaves NOI file
* 1PSAnfk2wftZlmY17ofYuBxAVrwM16nMF <- Chaves longlat file
* 1zlICr-bFfK_b36LYNQ_T24bt1iU0XKUR <- Eddy NOI file
* 1Kg4h7TcTiZaG22NqJWP-9kmemOC0YRNJ <- Eddy longlat

Read in files and merge based on column - (gets rid of nonmatching ones?)
"""

df1 = pd.read_excel('Chaves_NOIdates.xlsx');
df2 = pd.read_excel('Latlong_Chaves.xlsx');
df3 = df1.merge(df2, on=["ai_id"], how = "inner");

"""save to file"""

df3.to_excel('ChavesMerged.xlsx')

"""The code is working right but, data needs to be proof-read"""

